apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ template "event_exporter.fullname" . }}'
subjects:
- kind: ServiceAccount
  name: '{{ template "event_exporter.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: ClusterRole
  name: '{{ template "event_exporter.fullname" . }}'
  apiGroup: rbac.authorization.k8s.io
