apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ template "event_exporter.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: '{{ template "event_exporter.fullname" . }}'
