apiVersion: v1
kind: Service
metadata:
  name: '{{ template "event_exporter.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: '{{ template "event_exporter.fullname" . }}'
spec:
  ports:
    - name: '{{ template "event_exporter.fullname" . }}'
      port: '{{ .Values.port }}'
      protocol: TCP
      targetPort: 8090
  selector:
    name: '{{ template "event_exporter.fullname" . }}'
  sessionAffinity: None
  type: ClusterIP
